### ISSUE TITLE
Error after "Launching Session": Unable to load shared library 'pcoip_core' or one of its dependencies.

### ISSUE THREAD

**Issue by phelterhoff** [Nightmayr-snaps/amazon-workspaces-snap#3]
Since the last Update ( 4.5.0.2006 2023-02-06 (7) ) I cannot connect to my workspace any more

Logs:
```LOGS
2023-02-09T10:54:26.353Z { Version: "4.5.0.2006" }: [ERR] Session Provision failed: Autofac.Core.DependencyResolutionException: An exception was thrown while activating WorkSpacesClient.Gtk.InSession.Pcoip.GtkPcoipProtocolAdapter.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(WorkSpacesClient.Gtk.WindowManager.IGtkWindowManager, WorkSpacesClient.Common.Infrastructure.IDevice)' on type 'GtkPcoipProtocolAdapter'.
 ---> System.DllNotFoundException: Unable to load shared library 'pcoip_core' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpcoip_core: cannot open shared object file: No such file or directory
   at WorkSpacesClient.Gtk.InSession.Pcoip.GtkPcoipProtocolAdapter.pcoip_core_api_version_get()
   at WorkSpacesClient.Gtk.InSession.Pcoip.GtkPcoipProtocolAdapter..ctor(IGtkWindowManager windowManager, IDevice device) in /Users/jenkins/workspace/Singularity-Xamarin-Linux2/src/WorkSpacesClient.Gtk/InSession/Pcoip/GtkPcoipProtocolAdapter.cs:line 66
   at lambda_method525(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at WorkSpacesClient.Gtk.InSession.GtkSessionFactory.ConstructPcoipSession(PreparedResource resource) in /Users/jenkins/workspace/Singularity-Xamarin-Linux2/src/WorkSpacesClient.Gtk/InSession/GtkSessionFactory.cs:line 33
   at WorkSpacesClient.Gtk.UseCases.PcoipSessionProvisionUseCase.PcoipSessionProvisionRouter.NavigateToStreamingUseCase(PreparedResource resource) in /Users/jenkins/workspace/Singularity-Xamarin-Linux2/src/WorkSpacesClient.Gtk/UseCases/PcoipSessionProvisionUseCase/PcoipSessionProvisionRouter.cs:line 42
   at WorkSpacesClient.Common.UseCases.SessionProvisionUseCase.SessionProvisionPresenter.BeginUseCase() in /Users/jenkins/workspace/Singularity-Xamarin-Linux2/src/WorkSpacesClient.Common/UseCases/PcoipSessionProvisionUseCase/SessionProvisionPresenter.cs:line 70
   ```

I am using Kubuntu 22.04.
```LOG
snap --version
snap    2.58+22.04
snapd   2.58+22.04
series  16
ubuntu  22.04
kernel  5.15.0-60-generic
```

**Comment by Nightmayr** [comment]
I'll do some investigating on this over the weekend, hopefully will have a fix out soon

**Comment by Nightmayr** [comment]
It looked like one libpcoip's dependencies were outdated. Pushed a change https://github.com/Nightmayr-snaps/amazon-workspaces-snap/commit/b2573a67f81aaeed4c1b113e5c07451b0855678a that should get this working. Will be in the edge and stable channels shortly

**Comment by phelterhoff** [comment]
That helped, thanks for the quick fix.
